fix: Custom validation refactor
paypal/paypal-messaging-components pull request #11
Opened 2019-07-03 18:40 UTC by YSNIS

2019-07-03 19:10 UTC, Seavenly requested changes

2019-07-03 19:10 UTC, Seavenly commented on demo/index.html
> +                        markup: 'https://localhost.paypal.com:8080/custom.html'
We should probably refrain from committing changes to the demo pages, especially with for non-general use-cases.

2019-07-03 19:10 UTC, Seavenly commented on src/services/banner/customTemplate.js
> +    return markupProm.then(markup => markup);
It looks like we are accepting any `style.markup` value. We should probably ensure that a URL is used from `paypalobjects` or give a blank message.

2019-07-03 19:10 UTC, Seavenly commented on demo/custom.html
> +<style>
Do we want an example of this in our repo?

2019-07-03 19:10 UTC, Seavenly commented on src/models/Banner/index.js
> +                    insertMarkup // Promise<Object(meta)>
```suggestion
                    insertMarkup // Promise<Object(meta, options)>
```

2019-07-03 19:10 UTC, Seavenly commented on src/models/Banner/index.js
> +            const renderProm = getBannerMarkup(options) // Promise<Object({ markup, options })>
```suggestion
            const renderProm = getBannerMarkup(options) // Promise<Object(markup, options)>
```

2019-07-03 19:10 UTC, Seavenly commented on src/services/banner/index.js
> +            options = objectMerge(options, { ...bannerOptions });
Consider creating a new variable instead of reassigning the options reference.

2019-07-03 19:37 UTC, gillycheesesteak commented on src/services/banner/index.js
> +        return JSON.parse(annotationsString[1]);
Would it be valuable to wrap this in a `try { } catch { }` in case the contents of the comment are not valid JSON?

2019-07-03 19:37 UTC, gillycheesesteak commented on src/services/banner/index.js
> +            options = objectMerge(options, { ...bannerOptions });
Can `bannerOptions` be passed as-is as the second argument here?

2019-07-03 19:37 UTC, gillycheesesteak commented on src/services/banner/customTemplate.js
> +    return markupProm.then(markup => markup);
This can just be `return markupProm`, or could just return directly without declaring `markupProm`

2019-07-03 20:21 UTC, YSNIS commented on demo/index.html
> +                        markup: 'https://localhost.paypal.com:8080/custom.html'
Yeah I'm gonna revert this back.  For now though I wanted Ryan to have an easily accessible demo page to test the story.

2019-07-03 20:22 UTC, YSNIS commented on src/services/banner/customTemplate.js
> +    return markupProm.then(markup => markup);
I changed the regex to match htt[s://www.paypalobjects.com

2019-07-03 20:22 UTC, YSNIS commented on demo/custom.html
> +<style>
I think this can get reverted back along with the demo page.

2019-07-08 14:50 UTC, YSNIS commented on src/models/Banner/index.js
> +                    insertMarkup // Promise<Object(meta)>
Done.

2019-07-08 14:52 UTC, YSNIS commented on src/models/Banner/index.js
> +            const renderProm = getBannerMarkup(options) // Promise<Object({ markup, options })>
Done.

2019-07-08 14:55 UTC, YSNIS commented on src/services/banner/index.js
> +            options = objectMerge(options, { ...bannerOptions });
Done.

2019-07-08 15:12 UTC, YSNIS commented on src/services/banner/index.js
> +        return JSON.parse(annotationsString[1]);
Done.

2019-07-08 15:15 UTC, YSNIS commented on src/services/banner/index.js
> +            options = objectMerge(options, { ...bannerOptions });
Done.

2019-07-08 15:17 UTC, YSNIS commented on src/services/banner/customTemplate.js
> +    return markupProm.then(markup => markup);
Done.

2019-07-09 13:16 UTC, Seavenly commented on src/services/banner/index.js
> +            return bannerOptions;
Can't we just `return JSON.parse(annotationsString[1])`?

2019-07-09 13:16 UTC, Seavenly commented on src/services/banner/customTemplate.js
> +    let markupRegex = /https:\/\/www\.paypalobjects\.com/;
Is it feasible to use `String.prototype.startsWith()` instead of a regex for this scenario? And for `__DEMO__` we can just accept anything since it's for internal use only?

2019-07-09 13:16 UTC, Seavenly commented on src/services/banner/customTemplate.js
> +    let markupRegex = /https:\/\/www\.paypalobjects\.com/;
Also, have we considered how this will work with the customization app since everything is now some form of URL?

2019-07-09 14:12 UTC, YSNIS commented on src/services/banner/index.js
> +            return bannerOptions;
Yup - remnant of some previous code.

2019-07-09 15:27 UTC, Seavenly approved these changes

2019-07-09 15:29 UTC, gillycheesesteak approved these changes

2019-07-09 16:59 UTC, merged