feat: add Pay in 4 text messages
paypal/paypal-messaging-components pull request #275
Opened 2020-09-08 21:18 UTC by yeul

2020-09-15 14:04 UTC, merlinpatt requested changes
One other thing I noticed, and I'll send you a screenshot, is that when I put in an amount for PI4Q, it put a weird bracket in the calculated amount. Also the amount seems to be dividing by 12 when it should be by 4.

2020-09-15 14:04 UTC, merlinstardust commented on server/locale/US/PPC/validOptions.js
> -import { Types } from '../../types';
Do we have root imports? Might be a good a time to add them. `~/server/types` would be a lot nicer.

2020-09-15 14:04 UTC, merlinstardust commented on server/locale/US/Pi4/logos.js
> +    PRIMARY: {
Can these be named similarly to what I have on updates with `STACKED`, `SINGLE_LINE`, and so on? Would be clearer to know which is which.

If the `PRIMARY` or similar label is absolutely necessary for something (like custom banners), it could be added as another key-value of `PRIMARY: STACKED` or what have you

2020-09-15 14:04 UTC, merlinstardust commented on server/locale/US/Pi4/mutations/index.js
> +            return typeof amount === 'undefined' ? pi4_no_amount[type] : pi4_non_qual[type];
Are these different enough to warrant separate files? Looking at the diff between them, seems like a lot is extremely similar.

But if it does warrant separate files for mutations, I feel like there should be a corresponding banner

2020-09-15 14:04 UTC, merlinstardust commented on server/locale/US/Pi4/mutations/index.js
> +import pi4q from './pi4q';
I think these file name should align with the `banners/...` file names. That way it's clear which banner/info goes with which mutations

2020-09-15 14:04 UTC, merlinstardust commented on server/locale/US/Pi4/mutations/mediaQueries.js
> +    return `@media screen and (max-width: ${breakpoint}px) {
Is it at all possible to invert this (and the other queries) and the corresponding styles so `min-width` is used and it's a mobile first approach?

We use mobile first in almost every other media query except for the messageDisclaimer one and that's at a super small breakpoint too. So if possible, use min-width / mobile-first instead of max-width

2020-09-15 14:04 UTC, merlinstardust commented on server/locale/US/Pi4/mutations/mediaQueries.js
> +
Minor thing but there's an extra newline here. To be consistent, there should be either no extra newlines or one at each end of the media block

2020-09-15 14:04 UTC, merlinstardust commented on server/locale/US/Pi4/mutations/mediaQueries.js
> +
Also extra newline here

2020-09-15 14:04 UTC, merlinstardust commented on server/locale/US/Pi4/styles/text/base.css
> +.message__disclaimer > .tag--default > span {
Are these styles not being inherited from the existing base css that I added in `message-updates` branch?

2020-09-15 14:04 UTC, merlinstardust commented on server/locale/index.js
> +const getLocaleSettings = (offerCountry, id) => {
What goes in for id? Can this be clarified with a comment and example or use a different word? 

I've started to realize that ID is actually meaningless since literally everything is an identifier

2020-09-15 14:04 UTC, merlinstardust commented on server/locale/index.js
> +const getLocaleSettings = (offerCountry, id) => {
Looking below, it looks like ID is offerType, so I think you should just use that

2020-09-15 14:04 UTC, merlinstardust commented on tests/functional/spec/US/text.test.js
> +                [10, 12, 16].forEach(size => {
Do we not want to do 11, 13, 14, and 15 too?

2020-09-15 14:04 UTC, merlinstardust commented on tests/functional/spec/US/text.test.js
> +        const amounts = [undefined, 5];
This array of amounts should be defined closer to where it's used.

2020-09-15 14:04 UTC, merlinstardust commented on tests/functional/spec/US/text.test.js
> +        const accountTest = amount =>
This seems weird to defined this long function inside of the `accounts.forEach` block. Any way to define it before the block so you can just do the below or similar.

```
accounts.forEach(account => {
  amounts.forEach(amount => {
    if (account === 'DEV0000000PI4') accountTest(account, amount)
    else accountTest(account, amount)
  }
}
```

Other option would be to change getConfig to just have a conditional in the `getConfig` function:

```
const getConfig = style => {
    const config = {
        account,
        style: {
            layout: 'text',
            ...style
        }
    };
    if (account === 'DEV0000000PI4') {
        config.amount = 5;
    }
    return config;
);
```

2020-09-15 14:04 UTC, merlinstardust commented on utils/devServerProxy/miscellaneous.js
>              return baseFormat.replace(/^([\d,]+)(\.)(\d+)$/, (match, p1, p2, p3) => `${p1.replace(/,/g, '.')},${p3}`);
Why did this line get moved up to DE?

2020-09-15 14:09 UTC, yeul commented on utils/devServerProxy/miscellaneous.js
>              return baseFormat.replace(/^([\d,]+)(\.)(\d+)$/, (match, p1, p2, p3) => `${p1.replace(/,/g, '.')},${p3}`);
This was moved up to DE because it was causing GB to have a ',' instead of a '.' in its amount. The only time there should be a comma is when the country is DE since that is how they format their currency.

2020-09-15 14:20 UTC, yeul commented on tests/functional/spec/US/text.test.js
> +                [10, 12, 16].forEach(size => {
This actually existed prior to my changes and was just the way the text.test file was set up. I believe the logic behind it when Ryan created it was that it was safe to test the smallest, the default, and the largest as they are most likely to be used and if those are okay, the likelihood of the others being okay too is high.

2020-09-15 14:55 UTC, yeul commented on server/locale/US/Pi4/mutations/index.js
> +import pi4q from './pi4q';
I named it after the `offerType` inside the pay_in_four and pay_in_four_q banners since PI4 and PI4Q are used in devServerProxy and it keeps with that convention. I could totally add a clarifying comment though, otherwise the names would be super long i.e. pay_in_four_non_qual.js and pay_in_four_no_amount.js. How about this?

```
/**
 * pi4_no_amount and pi4_non_qual correspond to the message pay_in_four.json
 * pi4q corresponds to the message pay_in_four_q.json
 */
```

2020-09-15 16:07 UTC, yeul commented on server/locale/US/Pi4/styles/text/base.css
> +.message__disclaimer > .tag--default > span {
Yup they totally are, this was a placeholder until your changes came through so I cam remove it now!

2020-09-16 16:54 UTC, merlinpatt commented on server/locale/US/Pi4/mutations/index.js
> +import pi4q from './pi4q';
The comment helps 👍

2020-09-16 17:42 UTC, merlinpatt commented on tests/functional/spec/US/text.test.js
> +        const accountTest = amount =>
```
accounts.forEach(account => {
  if (account === 'DEV0000000PI4') {
    amounts.forEach(amount => {
      accountTest(account, amount);
    }
  }
  else {
    accountTest(account, amount)
  }
}
```

2020-09-16 19:42 UTC, yeul commented on server/locale/index.js
> +const getLocaleSettings = (offerCountry, id) => {
I've gone ahead and renamed it to `offerType`.

2020-09-23 17:05 UTC, merlinpatt approved these changes

2020-09-23 17:07 UTC, merged