feat: US GPL modal
paypal/paypal-messaging-components pull request #284
Opened 2020-09-15 13:12 UTC by gillycheesesteak

2020-09-16 14:52 UTC, merlinpatt requested changes

2020-09-16 14:52 UTC, merlinstardust commented on src/components/modal/content/DE/parts/Calculator.jsx
> +import { useCalculator, useContent } from '../../../lib';
This triple `../` makes a good case for us using an aliased root import. It's a little hard to follow

2020-09-16 14:52 UTC, merlinstardust commented on src/components/modal/content/DE/parts/Calculator.jsx
> +                <h3 className="title">{content.calculator.title}</h3>
Given how often the subfields of `content` and `terms` are called, it would be good to extract them to simplify the code a bit

2020-09-16 14:52 UTC, merlinstardust commented on src/components/modal/content/DE/parts/Disclaimer.jsx
> +import { useContent } from '../../../../lib';
Oof... this quadruple `../` is even worse. We definitely need some root importing

2020-09-16 14:52 UTC, merlinpatt commented on src/components/modal/content/DE/parts/Disclaimer.jsx
> +        const disclosure = Number(offer.apr.replace(/[,.]/g, '')) === 0 ? content.disclosure0 : content.disclosure;
1. Would be good to abstract `Number(offer.apr.replace(/[,.]/g, '')) === 0` to something like `isZeroApr` just to make this a little clearer. Took me a minute to figure out what this was doing

2. Can `disclosure0` be renamed to `disclosureFor0Apr` or similar? My first thought was this some kind of strangely represented array

2020-09-16 14:52 UTC, merlinpatt commented on src/components/modal/content/DE/parts/INST.jsx
> +            {/* <!-- Calculator --> */}
While I usually prefer more comments and not less, this one seems unnecessary. The `Calculator` component and `calculator-container` class make it very obvious

2020-09-16 14:52 UTC, merlinpatt commented on src/components/modal/content/DE/parts/TermsTable.jsx
>      if (+terms.amount < terms.minAmount && terms.type === 'pala') {
Similar to above, the subfields of `terms` could be pulled out.

Also, what's the initial `+` do? It's been a while since I have had to use that

2020-09-16 14:52 UTC, merlinpatt commented on src/components/modal/content/DE/styles/header.scss
> +.header-wrapper {
+1000 for SCSS. So beautiful.

2020-09-16 14:52 UTC, merlinpatt commented on src/components/modal/parts/Tabs.jsx
>      // TODO: Accessibility
So I know this was already here, but do you know what needs to be done in terms of accessibility and can you add it here with this comment?

I don't think it should be incorporated into your story, but I think if the comment had more detail, the next dev to see it would be more encouraged to try to make this accessible

2020-09-25 15:01 UTC, Seavenly commented on src/components/modal/content/DE/parts/Calculator.jsx
> +import { useCalculator, useContent } from '../../../lib';
We would love to do this, but I believe we are currently limited by the common SDK webpack config that we utilize.

2020-09-25 15:06 UTC, merged