feat: Add fontFamily and fontSrc
paypal/paypal-messaging-components pull request #398
Opened 2020-12-08 14:51 UTC by jadutter

Add fontFamily and fontSrc option to text layout.

Allow merchants to pass fontFamily and fontSrc options in order to customize the font for upstream messages.

2020-12-13 21:46 UTC, merlinpatt requested changes
The code itself looks pretty good. I'm still having trouble trying to get a fontSrc to load on my machine. Would be worth having another dev or two also try to test it on their machine.

Also, be sure to commit via the command line, so the pre-commit linting check runs. I found the following after running `npm run lint`

```
server/validateStyle.js
  29:24  error    'fontSrc' is already declared in the upper scope  no-shadow
  84:17  warning  Unexpected console statement                      no-console

src/zoid/message/validation.js
  127:17  warning  Unexpected console statement                          no-console
  128:17  error    Assignment to property of function parameter 'style'  no-param-reassign
  130:24  error    Assignment to property of function parameter 'style'  no-param-reassign

✖ 5 problems (3 errors, 2 warnings)
```

2020-12-13 21:46 UTC, merlinstardust commented on server/locale/DE/validOptions.js
> +        }
For flex, I think we can simplify this to just have it be `flex.fontFamily` and `flex.fontSrc`. Color options can just be handled at `flex.color`.

2020-12-13 21:46 UTC, merlinstardust commented on server/locale/GB/validOptions.js
> +            fontSrc: [Types.MULTI_STRING]
As above, we can flatten this and not need `flex.text`, which could also be confusing

2020-12-13 21:46 UTC, merlinstardust commented on server/locale/US/GPL/validOptions.js
> +            fontSrc: [Types.MULTI_STRING]
As above, we can flatten this and not need `flex.text`

2020-12-13 21:46 UTC, merlinstardust commented on server/locale/US/GPL/validOptions.js
> +            fontSrc: [Types.MULTI_STRING]
We shouldn't need these fields in custom, since custom gets defined with a URL pointing to custom HTML files. Ideally, if they're using `fontFamily` or `fontSrc`, they won't need to repeat it in custom

2020-12-13 21:46 UTC, merlinstardust commented on server/locale/US/PPC/validOptions.js
> +            fontSrc: [Types.MULTI_STRING]
As above, we can flatten this and not need `flex.text`

2020-12-13 21:46 UTC, merlinstardust commented on server/locale/US/PPC/validOptions.js
> +            fontSrc: [Types.MULTI_STRING]
As above, custom shouldn't need these

2020-12-13 21:46 UTC, merlinstardust commented on server/locale/DE/validOptions.js
> +        }
`fontSrc` should be fully spelled out as `fontSource`. It's better to use full spellings unless the abbreviation is extremely long.

2020-12-13 21:46 UTC, merlinstardust commented on server/message/index.jsx
> +const getFontSrcRule = fontSrc => {
This function is getting repeated a lot here and in `server/validateStyle` and in `src/zoid/message/validation`, so I think it should be abstracted to not repeat as much code.

2020-12-13 21:46 UTC, merlinstardust commented on server/message/index.jsx
> +                const fmt = fontFormats[ext];
`ext` and `fmt` should be `extension` and `format`

2020-12-13 21:46 UTC, merlinstardust commented on server/message/index.jsx
> +        // svg: 'svg' // svg
Since we're ignoring `woff2`, `eot`, and `svg`, these can be removed.

2020-12-13 21:46 UTC, merlinstardust commented on server/message/index.jsx
> +    if (fontSrc?.constructor === Array) {
This check shouldn't be necessary since we're already forcing an array at the validate step

2020-12-13 21:46 UTC, merlinstardust commented on server/message/index.jsx
> +const getFontSrcRule = fontSrc => {
Add newline before the function

2020-12-13 21:46 UTC, merlinstardust commented on server/message/index.jsx
> +    }
All these font lines have made it more difficult to read. I think moving all of it in to a function will make it more readable

2020-12-13 21:46 UTC, merlinstardust commented on server/message/index.jsx
> +.message__messaging .message__disclaimer span`;
Indent these and move the closing backtick to the next line so it looks cleaner

2020-12-13 21:46 UTC, merlinstardust commented on server/message/index.jsx
> +            }`);
This can fit on one line

2020-12-13 21:46 UTC, merlinstardust commented on server/validateStyle.js
> +function validateFontSrc(fontSrc) {
Add newline before and after the function

2020-12-13 21:46 UTC, merlinstardust commented on server/message/index.jsx
> +        : '';
In the case that a merchant wants to use a generic font family, then `fontFamily` should not have quotes as generic families are keywords. It should still have quotes when not generic.

Here's an array of generic font-families I found on MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/font-family

```
['serif', 'sans-serif', 'monospace', 'cursive', 'fantasy', 'system-ui', 'ui-serif', 'ui-sans-serif', 'ui-monospace', 'math', 'emoji', 'fangsong']
```

2020-12-13 21:46 UTC, merlinpatt commented on src/zoid/message/validation.js
> +                console.log(`fontSrc:`, fontSrc);
Remove console.log artifacts

2020-12-13 21:46 UTC, merlinpatt commented on server/validateStyle.js
> +                console.log(val);
Remove console.log artifacts

2020-12-14 19:30 UTC, jadutter commented on server/locale/GB/validOptions.js
> +            fontSrc: [Types.MULTI_STRING]
I’ll admit, I found it confusing too. It took me a bit to recognize we were structuring the object default slightly differently than the input object we’re comparing it against. I figured it was better to follow the convention we were using.

If we moved flex.text.fontSource to flex.fontSource, then I think text.text.fontSource should likewise move to text.fontSource.

Ditto for fontFamily.

2020-12-14 20:03 UTC, jadutter commented on server/message/index.jsx
> +        : '';
I'll add a function to check if they're using one of those generic names.

2020-12-23 16:37 UTC, Seavenly commented on server/message/index.jsx
> +        const fontSource = val;
Can the parameter `val` just be renamed to `fontSource`?

2020-12-23 16:37 UTC, Seavenly commented on server/message/index.jsx
> +    const urlPattern = RegExp(`^(?<url>https?://.+?.(?<ext>${[...Object.values(fontFormats)].join('|')}))$`);
It doesn't look like we're actually using the named capture groups. Would it be sufficient without them? Also, are we not supporting relative paths?

2020-12-23 16:37 UTC, Seavenly commented on server/message/index.jsx
> +        const ruleVal = (fontSource?.constructor === Array ? fontSource : [fontSource])
Consider using the more declarative `Array.isArray()`

2020-12-23 16:37 UTC, Seavenly commented on server/message/index.jsx
> +            .filter(e => typeof e === 'string')
At this point, these input aspects should have been vetted. Can these be removed?

2020-12-23 16:37 UTC, Seavenly commented on server/message/index.jsx
> +                const extension = match ? match[2] : null;
```suggestion
                const extension = urlPattern.exec(url)?.[2];
```

2020-12-23 16:37 UTC, Seavenly commented on server/message/index.jsx
> +                if (url && format) {
We should be able to safely assume `url` exists at this point.
``` suggestion
                if (format) {
```

2020-12-23 16:37 UTC, Seavenly commented on server/message/index.jsx
> +            .filter(e => e)
```suggestion
            .filter(Boolean)
```

2020-12-23 16:37 UTC, Seavenly commented on server/message/index.jsx
> +        error: null
Can we just omit the `error` value completely unless it exists?

2020-12-23 16:37 UTC, Seavenly commented on server/message/index.jsx
> +    const fontPattern = RegExp(/^(?<font>([a-zA-Z0-9._-]\s*)+?)$/);
Do we need to validate the font here when it should have been vetted prior to this?

2020-12-23 16:37 UTC, Seavenly commented on server/message/index.jsx
> +    };
It looks like this is needed because the generic font families can't be surrounded with `'`s, but specific font names should be to capture spaces. Can we add a comment explaining this reasoning Do we need to have `math`, `emoji`, and `fangsong` in the list?

2020-12-23 16:37 UTC, Seavenly commented on server/message/index.jsx
> +    const fontFamily = typeof val === 'string' ? genericFamilies[val] ?? `'${val}'` : '';
It should be safe to assume `val` is a string from prior vetting.

2020-12-23 16:37 UTC, Seavenly commented on src/utils/elements.js
> +            }
Instead of 2 try blocks consider just using `return flattenedToObject(name, JSON.parse(value.replace(/'/g, '"')));` since it will cover both cases.

2020-12-23 16:37 UTC, Seavenly commented on src/utils/elements.js
> +        if (name === 'style-text-fontSource' && value?.indexOf('[') >= 0) {
Consider using `String.prototype.startsWith` as opposed to `indexOf() >= 0`. It requires importing the polyfill manually from `core-js-pure` but it's generally preferred due to its declarative nature.

2020-12-23 17:48 UTC, jadutter commented on server/message/index.jsx
> +    const urlPattern = RegExp(`^(?<url>https?://.+?.(?<ext>${[...Object.values(fontFormats)].join('|')}))$`);
No, we wouldn't want to support relative pathing. Since this goes into our iframe, it would grab the path relative to our iframe. 
To support relative urls, we'd likely need to modify it so that fontSource values get checked and appended with the page origin before the request went out to cpnw. 

I'd initially tried pulling out the named capture groups, but it seems they're not supported in regular babel. I wasn't sure if it was acceptable to add `@babel/plugin-transform-named-capturing-groups-regex` to the sdk, so I refactored it to pull out the items by index. 
I'd be more than happy to use named capture groups for this instead.

2020-12-23 17:52 UTC, jadutter commented on server/message/index.jsx
> +        const fontSource = val;
Yes. In previous commits, I was changing what was stored in fontSource, so I was trying not to modify the input parameter. I'll simplify this.

2020-12-23 17:55 UTC, jadutter commented on server/message/index.jsx
> +        const ruleVal = (fontSource?.constructor === Array ? fontSource : [fontSource])
I made the change to my local copy after you mentioned the same thing on cpnw.

2020-12-23 18:09 UTC, jadutter commented on server/message/index.jsx
> +                const extension = match ? match[2] : null;
Updated.

2020-12-23 18:12 UTC, jadutter commented on server/message/index.jsx
> +            .filter(e => e)
Updating here, and other locations where I was filtering for truthy values.

2020-12-23 18:14 UTC, jadutter commented on server/message/index.jsx
> +    const fontPattern = RegExp(/^(?<font>([a-zA-Z0-9._-]\s*)+?)$/);
We don't need it anymore. I'll remove it.

2020-12-23 18:19 UTC, jadutter commented on server/message/index.jsx
> +    };
This list was pulled from MDN's list of generic names, without further thought. 

I think we can safely drop `math` and `emoji`, but we may want to retain `fangsong` to future proof needing to support chinese fonts.

2020-12-23 20:34 UTC, jadutter commented on server/message/index.jsx
> +    const urlPattern = RegExp(`^(?<url>https?://.+?.(?<ext>${[...Object.values(fontFormats)].join('|')}))$`);
Keeping this as is since we cannot add the babel plugin for regex named groups.

2021-01-20 14:07 UTC, merged

2021-01-27 17:56 UTC, Seavenly commented
:tada: This PR is included in version 1.17.0 :tada:

The release is available on [GitHub release](https://github.com/paypal/paypal-messaging-components/releases/tag/v1.17.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: