feat: add GPL France text messages
paypal/paypal-messaging-components pull request #399
Opened 2020-12-10 21:03 UTC by yeul

2020-12-11 20:46 UTC, jadutter approved these changes

2020-12-14 00:22 UTC, merlinpatt requested changes
Code looks solid. Only had a few comments/questions

2020-12-14 00:22 UTC, merlinpatt commented on banners/FR/gplq.json
> +    "headline": [[["Payez en 4X."], ["default", "small"]]],
I think there should be an option text for non-qualifying amounts here?

`Payez en 4X pour les achats de 50 € à 2000 €.`

2020-12-14 00:22 UTC, merlinpatt commented on server/locale/FR/mutations/gpl.js
> +            'logo.type:alternative',
Is alternative right supposed to have the logo on the right side? If it is, I'm not seeing it show up on the right. If not, then ignore this.

2020-12-14 00:22 UTC, merlinpatt commented on server/locale/FR/mutations/common.js
> +    ['text.color:white && logo.type:primary', { logo: Logo.PP_PAYPAL.WHITE }],
Since this file only ever contains logo mutations, what do you think about switching the file name to `logos.js` or `logoMutations.js`?

Also, given that we're using the same definition for almost every locale (except DE, I think), maybe we should just have this be a shared mutations file by default? And then it can be overridden by a specific locale?

2020-12-14 13:06 UTC, yeul commented on banners/FR/gplq.json
> +    "headline": [[["Payez en 4X."], ["default", "small"]]],
Eventually, but not for launch, there will be a third message created for non-qualifying amounts that have the min and max in the message.

2020-12-14 13:10 UTC, yeul commented on server/locale/FR/mutations/gpl.js
> +            'logo.type:alternative',
Nope! We're just following the same convention as GPL US and GB where alternative right is ignored. It might become a thing when we add text alignment to the messages though, but for now it should always be on the left.

2020-12-14 13:13 UTC, yeul commented on server/locale/FR/mutations/common.js
> +    ['text.color:white && logo.type:primary', { logo: Logo.PP_PAYPAL.WHITE }],
Good idea, I'll call it `logoMutations` and move it to the message folder and fix the imports for the GPL messages.

2020-12-23 17:24 UTC, yeul commented
- Correct link to @paypal-are's GPL FR Flex messages PR for reference: https://github.com/yeul/paypal-messaging-components/pull/9
- Correct link to my GPL FR modal PR for reference: https://github.com/yeul/paypal-messaging-components/pull/8

2020-12-23 17:28 UTC, merged