feat: standalone modal support
paypal/paypal-messaging-components pull request #402
Opened 2020-12-15 13:41 UTC by Seavenly

2020-12-17 14:18 UTC, merlinpatt approved these changes
Existing code and tests look good mostly except for the one small change I had. Plus I had a few thoughts beyond that

1. Can you add a functional test for this?
2. Since this feature is called standalone modal, I feel like we should rename the `demo/standalone.html` file to something else to prevent confusion.
3. Maybe this should get its own demo page like `demo/standalone_modal.html`? Thoughts?

2020-12-17 14:18 UTC, merlinpatt commented on src/components/modal/lib/utils.js
> +                'EZP'
Small thing but can EZP be put first so all the offers starting with EZP are together?

2020-12-17 14:19 UTC, merlinpatt requested changes
Accidentally hit approve on the last one, so comments are the same, but clicking request this time.

2021-01-25 20:39 UTC, gillycheesesteak commented on src/controllers/message/setup.js
> +        const { ...inlineScriptOptions } = getInlineOptions(script);
Can this be changed to `const inlineScriptOptions = ...`

2021-02-03 16:25 UTC, gillycheesesteak approved these changes

2021-03-09 19:05 UTC, merged

2021-03-10 16:43 UTC, Seavenly commented
:tada: This PR is included in version 1.20.0 :tada:

The release is available on [GitHub release](https://github.com/paypal/paypal-messaging-components/releases/tag/v1.20.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: