feat: DE banners
paypal/paypal-messaging-components pull request #48
Opened 2019-08-27 13:17 UTC by gillycheesesteak

2019-09-06 14:55 UTC, Seavenly requested changes

2019-09-06 14:55 UTC, Seavenly commented on src/interface/messages.js
> +                ...getInlineOptions(script)
Is this change necessary?

2019-09-06 14:55 UTC, Seavenly commented on src/messages/models/Banner/index.js
> +                console.error(err);
Can this be removed?

2019-09-06 14:55 UTC, Seavenly commented on src/messages/models/Banner/types.js
> +export default {
Since we've extracted the types into their own module, should we also extract the `validateType()` function from `validateOptions.js` into the same location as more of a types helper module?

2019-09-06 14:55 UTC, Seavenly commented on src/messages/models/Container/setSize.js
> +            if (container.getAttribute('data-pp-message-overflow') === 'fallback') {
Did we ever land anywhere with having a default set of options to check against based on locale to prevent unnecessary rerender attempts if the smallest style combination has already been selected?

2019-09-06 14:55 UTC, Seavenly commented on src/messages/models/Container/stats.js
> +        track(payload, container.getAttribute('data-pp-message-hidden') === 'hidden');
Should this be `data-pp-message-overflow`?

2019-09-06 14:55 UTC, Seavenly commented on src/messages/models/Template/index.js
> +    const localeClass = `locale--${__MESSAGES__.__LOCALE__}`;
Should we include this constant as part of the `locale` module?

2019-09-06 14:55 UTC, Seavenly commented on src/messages/models/Template/index.js
> +        mutationRules.logo.forEach(logo => appendImage(logoContainer, logo, 'PayPal Credit logo'));
Is it possible to have `appendImage()` handle the array check since both `appendText()` and `prependText()` handle that same logic internally.

2019-09-06 14:55 UTC, Seavenly commented on src/messages/models/Template/styles/index.js
> +    styles['layout:custom'] = custom;
If we're going to switching to a dynamic plugin type architecture, I wonder if these could be plugin rule sets as well.

2019-09-06 14:55 UTC, Seavenly commented on tests/unit/spec/src/messages/models/Banner/validateOptions.test.js
> -                ...validOptions,
We need to remember that some of this code involving the use of the `countryCode` option may return since the webpack variable solution will not be supported as we'd hoped.

2019-09-10 13:16 UTC, gillycheesesteak commented on src/messages/models/Banner/index.js
> +                console.error(err);
It was useful in my debugging, and will be tree-shaken in the prod build, so I think it makes sense to leave it in

2019-09-17 15:48 UTC, Seavenly commented on demo/standalone.html
> +        <script src="./messaging.js" data-pp-account="DEV0000000IAZ" data-pp-country="DE"></script>
Is `data-pp-country="DE"` being used?

2019-09-17 15:48 UTC, Seavenly commented on src/locale/DE/validOptions.js
> +        color: [Types.STRING, ['blue', 'black', 'white', 'white-no-border', 'gray|grey']],
Are we removing `'white-no-border'` from DE?

2019-09-17 15:48 UTC, Seavenly commented on src/locale/DE/validOptions.js
> +    custom: {
Should we remove this since it will not be a use-case at launch?

2019-09-17 15:48 UTC, Seavenly commented on tests/unit/spec/src/messages/models/Banner/validateOptions.test.js
> +    it('Allows valid id, _legacy, account, amount, country, style', () => {
Are we using a `country` prop anywhere?

2019-09-17 15:48 UTC, Seavenly commented on tests/utils/setup.js
> +window.__MESSAGES__ = {
Is this necessary because webpack isn't involved so the stand-in global variables aren't being replaced? Should we just import all the variables in `globals.js` into the window object?

2019-09-17 15:49 UTC, gillycheesesteak commented on src/locale/DE/validOptions.js
> +        color: [Types.STRING, ['blue', 'black', 'white', 'white-no-border', 'gray|grey']],
Yes

2019-09-17 15:51 UTC, Seavenly commented on tests/utils/setup.js
> +window.__MESSAGES__ = {
Alternatively, can they be injected with the `globals` field in the Jest config?

2019-09-18 15:07 UTC, Seavenly approved these changes

2019-09-18 15:18 UTC, merged