refactor: modify message update call to use smart/message
paypal/paypal-messaging-components pull request #545
Opened 2021-06-25 22:16 UTC by danzhaas

supplements PR of same name in CPNW

2021-07-02 14:26 UTC, rosman21 requested changes

2021-07-02 14:26 UTC, rosman21 commented on src/components/message/Message.jsx
> +            const dataObject = JSON.parse(data.slice(data.indexOf('<!-- ') + 5, data.indexOf(' -->')));
was there a reason you changed this from the code that looked for the HTML comment? I guess my worry with this is if somehow the comment is modified with like an extra `-` or something would it throw this check off? just being very picky but also curious

2021-07-02 14:26 UTC, rosman21 commented on demo/standalone.html
> +            paypal
I think this should be commented out and moved back to its original code

2021-07-02 18:41 UTC, danzhaas commented on src/components/message/Message.jsx
> +            const dataObject = JSON.parse(data.slice(data.indexOf('<!-- ') + 5, data.indexOf(' -->')));
So I changed it from the code which found the re-render script in the comment by searching the HTML nodes because  that required parsing the response as an HTML document and thus running 4 non-commented scripts, which are for rendering not re-rendering.  Does that make sense?
Your concern is valid; let me think about what can be done.

2021-07-06 16:07 UTC, gillycheesesteak commented on tests/unit/spec/src/components/message/Message.test.js
> +            } -->
This probably should be `JSON.stringify`-ed

2021-07-06 21:58 UTC, danzhaas commented
Will unskip and adjust Message.test.jsx as necessary upon approval of changes

2021-07-13 12:57 UTC, rosman21 submitted a review, later dismissed

2021-07-13 12:58 UTC, rosman21 commented
@danzhaas looks good. just waiting for next steps, go ahead and update that test though. if you need help lmk

2021-07-13 13:57 UTC, danzhaas commented
I see I took a step backwards here, so do not merge - fixing this now

2021-07-19 20:53 UTC, gillycheesesteak approved these changes

2021-08-03 18:11 UTC, rosman21 approved these changes

2021-09-14 22:47 UTC, merged

2021-09-15 18:21 UTC, Seavenly commented
:tada: This PR is included in version 1.26.3 :tada:

The release is available on [GitHub release](https://github.com/paypal/paypal-messaging-components/releases/tag/v1.26.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: