refactor: use separate storage key for device ID
paypal/paypal-messaging-components pull request #588
Opened 2021-08-12 19:11 UTC by gillycheesesteak

After conversation with @bluepnume, we want to update the field in storage that we use so we don't disturb the original storage ID. We will attempt to use this new ID if it is available, and fall back to the original storage ID if not. Also, we want to only use the child ID if it is persistent (ie the state is not fresh)

2021-08-12 19:56 UTC, rosman21 commented on src/components/message/Message.js
> +        deviceID: isStorageFresh() ? null : getDeviceID()
just curious but would it make more sense to just add parentDeviceId here instead of setting it to null? It looks like eventually it will be replaced later in the code but this is more just me being curious rather than a suggestion/code change

2021-08-13 13:20 UTC, rosman21 approved these changes

2021-08-16 16:14 UTC, rosman21 requested changes

2021-08-16 16:14 UTC, rosman21 commented on src/utils/sdk.js
> +    getSDKStorage,
library is failing because this doesn't seem to be an exported function 
https://github.com/paypal/paypal-sdk-client/blob/189b6f035845d9cd9f4fd5b804ff17c087b614ac/src/session.js#L8

2021-08-16 16:22 UTC, rosman21 approved these changes

2021-08-26 14:26 UTC, paypal-are approved these changes

2021-09-14 17:34 UTC, merged

2021-09-15 18:21 UTC, Seavenly commented
:tada: This PR is included in version 1.26.3 :tada:

The release is available on [GitHub release](https://github.com/paypal/paypal-messaging-components/releases/tag/v1.26.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: