feat: DE Pi30 modal
paypal/paypal-messaging-components pull request #601
Opened 2021-09-09 13:35 UTC by danzhaas

2021-09-15 13:48 UTC, rosman21 commented
Modals seem to render correctly, just need to resolve a lot of these conflicts @danzhaas

2021-09-15 13:51 UTC, rosman21 requested changes

2021-09-15 13:51 UTC, rosman21 commented on src/components/modal/content/DE-GPL/parts/ProductList.jsx
> +                {/* <div className="content-column product-buttons"> {productButtons}</div>
If this isn't being used i would just remove the commented out code

2021-09-15 13:51 UTC, rosman21 commented on src/components/modal/content/DE-GPL/parts/Pi30.jsx
> +                {/* <div className="content-column instructions transitional">{list}</div>
consider removing commented out code if not being used

2021-09-21 21:15 UTC, gillycheesesteak commented
Make sure to remove the stageTag build files @danzhaas

2021-09-21 21:20 UTC, gillycheesesteak commented on utils/devServerProxy/proxy.js
> +            if ((props.country === 'DE' && productNames.includes('gpl')) || productNames.includes('pi30')) {
```suggestion
            if (props.country === 'DE' && (productNames.includes('gpl') || productNames.includes('pi30')) {
```

2021-09-21 21:20 UTC, gillycheesesteak commented on src/components/modal/content/DE-GPL/parts/Content.jsx
> +            case '':
Is this `case` required?

2021-09-22 15:20 UTC, danzhaas commented on utils/devServerProxy/proxy.js
> +            if ((props.country === 'DE' && productNames.includes('gpl')) || productNames.includes('pi30')) {
Will fix

2021-09-22 15:25 UTC, danzhaas commented on src/components/modal/content/DE-GPL/parts/Content.jsx
> +            case '':
I suppose that line is not required, since the case where nothing is chosen would fall under default anyway.  Will remove that line.

2021-09-23 16:15 UTC, rosman21 commented on src/components/modal/content/DE-GPL/parts/Content.jsx
> -    // Product can be NONE when standalone modal so default to first product
Is this logic confirmed to be the right logic we want ?

2021-09-23 16:47 UTC, danzhaas commented on src/components/modal/content/DE-GPL/parts/Content.jsx
> -    // Product can be NONE when standalone modal so default to first product
Here is the plan for the modal logic:

**Modal Logic**
This section will outline the modal logic for displaying the both DE Pi30 and DE installments, as well as a description of the logic for these Credit Products 

**High level description of modal logic**

- All product-specific messages must open a modal for the product mentioned in the Pay Later message
- Pay in 30 days messages will open a Pay in 30 days tab within the modal
- GPL DE Installments messages will open the Installments tab within the modal
- All product-specific modals should give the customer a way to navigate to a modal to see all Pay Later products
- Since Installments product is not eligible until € 99+ transactions we could potentially link to the Non-qualifying installments modal 
- Could show non eligible amount in input field and let them change the amount in the modal to see the installments offers based on the inputted amount
- Affirm modal logic for multiple term lengths for monthly installments (threshold tab in spreadsheet).

Also, notes from Ryan: 

> I think the general rule is that the modal should match the message that was displayed, for its initial state and then what options are available from that initial state are based on the full suite of products eligible for that merchant/country

Also both Josh and Ryan said the NQ installments modal should show for amounts above 5000

2021-09-30 14:46 UTC, danzhaas commented on src/components/modal/content/DE-GPL/parts/ProductList.jsx
> +                {/* <div className="content-column product-buttons"> {productButtons}</div>
Done

2021-09-30 14:47 UTC, danzhaas commented on src/components/modal/content/DE-GPL/parts/Pi30.jsx
> +                {/* <div className="content-column instructions transitional">{list}</div>
Done

2021-09-30 15:26 UTC, danzhaas commented on src/components/modal/content/DE-GPL/parts/Content.jsx
> -    // Product can be NONE when standalone modal so default to first product
@rosman21 I think I misunderstood your question if it was specifically referencing line 24.  The wording on line 24 was confusing and is gone now.  To address your point, the logic is we default to the first & highest priority product (now on line 18) unless they're eligible for both GPL and PI30 and the amount is 0 or undefined, in which case the selectedProduct is set to 'none' and the product list is displayed (line 42).

2021-10-18 13:53 UTC, rosman21 approved these changes

2021-11-11 20:51 UTC, merged