feat: offer type preference config option
paypal/paypal-messaging-components pull request #62
Opened 2019-09-24 13:00 UTC by roja079

2019-09-24 18:28 UTC, Seavenly requested changes

2019-09-24 18:28 UTC, Seavenly commented on demo/standalone.html
> +            paypal
Can we revert changes to the demo page?

2019-09-24 18:28 UTC, Seavenly commented on src/messages/models/Banner/validateOptions.js
> +    validOptions.offer_type = validateType(Types.STRING, offer) ? offer : '';
We generally prefer camelCase variable names.

2019-09-24 18:28 UTC, Seavenly commented on src/messages/services/banner/index.js
> +            dimensions = LEGACY_NI_ONLY_PLACEMENT;
Consider this concise refactor:
``` javascript
const dimensions = typeEZP === '' || options.offer_type === 'NI' ? LEGACY_NI_ONLY_PLACEMENT : PLACEMENT;
```

2019-09-24 18:54 UTC, roja079 commented on demo/standalone.html
> +            paypal
Done

2019-09-24 18:55 UTC, roja079 commented on src/messages/models/Banner/validateOptions.js
> +    validOptions.offer_type = validateType(Types.STRING, offer) ? offer : '';
Done

2019-09-24 18:55 UTC, roja079 commented on src/messages/services/banner/index.js
> +            dimensions = LEGACY_NI_ONLY_PLACEMENT;
Done

2019-09-25 13:30 UTC, gillycheesesteak commented on src/messages/services/banner/index.js
> +        const dimensions = typeEZP === '' || options.offerType === 'NI' ? LEGACY_NI_ONLY_PLACEMENT : PLACEMENT;
Do we want to rename this placement const since it now serves multiple purposes?

2019-09-25 13:30 UTC, gillycheesesteak commented on src/messages/models/Banner/validateOptions.js
> +export default curry((logger, { account, amount, countryCode, style, offer, ...otherOptions }) => {
Do we want to validate the allowed values for this parameter here?

2019-09-25 14:12 UTC, roja079 commented on src/messages/models/Banner/validateOptions.js
> +export default curry((logger, { account, amount, countryCode, style, offer, ...otherOptions }) => {
No, we are allowing only string. If not string then we are setting it to empty string.

2019-09-25 14:12 UTC, roja079 commented on src/messages/services/banner/index.js
> +        const dimensions = typeEZP === '' || options.offerType === 'NI' ? LEGACY_NI_ONLY_PLACEMENT : PLACEMENT;
Done

2019-09-27 13:14 UTC, Seavenly approved these changes

2019-09-27 14:13 UTC, merged

2019-09-27 15:00 UTC, Seavenly commented
:tada: This PR is included in version 1.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@paypal/messaging-components)
- [GitHub release](https://github.com/paypal/paypal-messaging-components/releases/tag/untagged-fd1b87becd832e8a7cce)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: