feat: universal modal functional tests
paypal/paypal-messaging-components pull request #686
Opened 2021-12-20 16:41 UTC by yeul

2021-12-27 20:05 UTC, merlinpatt reviewed
overall looks good. Only had a few style/name comments

2021-12-27 20:05 UTC, merlinstardust commented on demo/snapshot/v2/sdk.html
> +            }, {});
Since we keep using mappedParams, maybe we make that a script we can pull in?

2021-12-27 20:05 UTC, merlinstardust commented on tests/functional/v2/config/US/content.config.js
> +                    ni: 'Pay over time with PayPal Credit'
What do you think about having this say `noInterest` instead of `ni`? Then it's easier to read and consistent with other keys.

2021-12-27 20:05 UTC, merlinstardust commented on tests/functional/v2/config/US/content.config.js
> +        maxAmount: '1500',
Why are these strings?

2021-12-27 20:05 UTC, merlinstardust commented on tests/functional/v2/config/US/content.config.js
> +    DEV_US_LONG_TERM_XO: {
I think this and NI don't need abbreviations. We can have them say `DEV_US_NO_INTEREST` and `DEV_US_LONG_TERM_CHECKOUT` to be more clear

2021-12-27 20:05 UTC, merlinstardust commented on tests/functional/v2/spec/api.test.js
> +    '%s API Modal Iframe %s',
I presume each `%s` corresponds to country and then account. Maybe have the test name more clearly split with dashes like `%s - API Modal Iframe - %s` or even `Country:%s - API Modal Iframe - Account:%s`

2021-12-27 20:05 UTC, merlinstardust commented on tests/functional/v2/spec/sdk.test.js
> +                        testNameParts(country, integration, account, amount, viewport)
Why is `testNameParts` called inside `testNameParts`?

2021-12-27 20:05 UTC, merlinpatt commented on tests/functional/v2/utils/setup.js
> +export const testNameParts = (country, integration, account, amount, viewport) => {
For ease of potential refactoring and so we don't have to remember order in future tests, I think it would be good if the param was an object with all those things in it.

Also since it outputs a testName, I think it can be renamed to `getTestName` or something more action-y.

2021-12-27 20:05 UTC, merlinpatt commented on tests/functional/v2/utils/setup.js
> +        .replace(/\s/g, '_');
What does `testName` look like?

2021-12-27 20:05 UTC, merlinpatt commented on utils/devServerProxy/config/US/index.js
> +    DEV_US_NI: {
DEV_US_NO_INTEREST

2021-12-28 21:24 UTC, merlinpatt commented on tests/functional/v2/config/index.js
> +export * from './US/content.config';
Had one more thought. Why is this exported as `*` if the `US` object is the only thing that would go in the `US/content.config` file?

Why not make `content.config` do a default export and then do `export {default as US} from './US'`

Why have `US/content.config` instead of just `US.js` or something?

2022-01-04 17:19 UTC, yeul commented on tests/functional/v2/spec/sdk.test.js
> +                        testNameParts(country, integration, account, amount, viewport)
Oops, good catch!

2022-01-05 14:58 UTC, yeul commented on tests/functional/v2/utils/setup.js
> +        .replace(/\s/g, '_');
I pushed up a change that adds a comment to this regex. But essentially if the test name is "Esc key closes modal", it removes the spaces and looks like ```Esc_key_closes_modal```. It's used as part of the id for the snapshot files, similar to our current functional tests.

2022-01-07 18:17 UTC, merlinpatt requested changes

2022-01-07 18:17 UTC, merlinstardust commented on tests/functional/v2/spec/api.test.js
> +    openNIView,
openNoInterestView

2022-01-07 18:17 UTC, merlinstardust commented on tests/functional/v2/spec/standalone.test.js
> +// NI
No Interest

2022-01-07 18:17 UTC, merlinstardust commented on tests/functional/v2/testFn/index.js
> +export * from './ni';
./noInterest

2022-01-07 18:17 UTC, merlinstardust commented on tests/functional/v2/testFn/ni.js
> +    ni: {
noInterest

2022-01-07 18:17 UTC, merlinstardust commented on tests/functional/v2/testFn/ni.js
> +export const openNIView = async (contentWindow, modalContent, testName) => {
openNoInterestView

2022-01-07 18:17 UTC, merlinstardust commented on tests/functional/v2/utils/selectors.js
> +    ni: {
noInterest

2022-01-07 18:17 UTC, merlinstardust commented on utils/devServerProxy/config/US/index.js
> +                template: 'niq.json',
no_interest_qualifying.json

2022-01-07 18:17 UTC, merlinstardust commented on utils/devServerProxy/config/US/index.js
> +                template: 'gplnq.json',
short_term.json

2022-01-07 18:17 UTC, merlinstardust commented on utils/devServerProxy/config/US/index.js
> +                template: 'gplq.json',
short_term_qualifying.json

2022-01-07 18:17 UTC, merlinpatt commented on utils/devServerProxy/config/US/index.js
> +                template: 'ni_v2.json',
no_interest

2022-01-19 15:06 UTC, merlinpatt approved these changes

2022-01-19 15:07 UTC, merged