feat: expand modal for api iframes
paypal/paypal-messaging-components pull request #690
Opened 2021-12-27 19:44 UTC by merlinpatt

2022-01-18 21:02 UTC, grablack requested changes

2022-01-18 21:02 UTC, grablack commented on src/components/modal/v2/styles/components/_header.scss
> +                width: 100%;
Looks like this width 100% is causing that transparent space on the lander iframe. If we can't use 900px we probably need to also have transform: translate(0, -35%); to cover the transparent space.

2022-01-18 21:02 UTC, grablack commented on src/components/modal/v2/parts/Container.jsx
> +    ].join(' ');
There are some extra spaces in the class. We can filter the empty responses.
`].filter(Boolean).join(' ');`

2022-01-21 14:25 UTC, merlinpatt commented on src/components/modal/v2/parts/Container.jsx
> +    ].join(' ');
There's a couple other places in the library (like `v2/parts/Button`) where we use a `.join` without a filter since extra spaces don't make a difference, so I'd like to leave it as is

2022-01-25 18:16 UTC, grablack approved these changes

2022-01-28 14:51 UTC, merlinpatt commented
US modal tests are failing because "Special Financing" bullet was removed.

2022-01-28 15:41 UTC, Seavenly commented on src/components/modal/v2/parts/BodyContent.jsx
> +        }
Thoughts on `window.document.querySelector('#close-btn')?.focus();`?

2022-01-28 15:41 UTC, Seavenly commented on src/components/modal/v2/parts/views/NI/styles.scss
> +                    max-width: $content-wrapper-max-width-api-iframe;
Can we instead include this in the `fixedWrapper` mixin with the other `max-width` definitions?

2022-01-28 15:41 UTC, Seavenly commented on src/components/modal/v2/parts/views/NI/styles.scss
> +                    }
Can we update the 2 `max-width: 640px` values in the tablet and mobile section to be `$content-wrapper-max-width-tablet`? That was likely an oversight before. And then should this be up one level and underneath both the `@include tablet` and `@include mobile` so that it follows the pattern of our other areas where we choose between the 3 `max-width` variables?

2022-01-28 15:41 UTC, Seavenly commented on src/components/modal/v2/styles/components/_body-content.scss
> +        margin: 0;
Is this `margin: 0` necessary since it looks to be `auto` above and the full width would prevent that from being any sort of issue.

2022-01-28 15:41 UTC, Seavenly commented on src/components/modal/v2/styles/components/_header.scss
> +            max-width: $content-wrapper-max-width-api-iframe;
Similar comment above where I think this style should ideally live inside the `fixedWrapper` mixin with the others.

2022-01-28 15:41 UTC, Seavenly commented on src/components/modal/v2/styles/components/_header.scss
> +                    }
Can we leave a brief comment above this that we're duplicating this style here because the `apiIframe` mixin has a higher priority than the original scroll below?

2022-02-02 18:49 UTC, merged