fix: edge caching TS cookie
paypal/paypal-messaging-components pull request #799
Opened 2022-04-21 16:04 UTC by paypal-rosman

in order to fix this we are grabbing the `ts_c` cookie from the zoid iframe, writing it to local storage, then appending it to the `meta.global` property in the log endpoint.

2022-04-25 19:11 UTC, gillycheesesteak commented on src/library/zoid/message/component.js
> +                            getCookieByName('ts_c') !== null
Should we put `getCookieByName('ts_c')` into a variable to reuse below?

2022-04-25 19:11 UTC, gillycheesesteak commented on src/library/zoid/message/component.js
> +                                : getCookieByName('ts_c');
In this case, `getCookieByName('ts_c')` will always be `null`, right?

2022-04-25 20:12 UTC, paypal-rosman commented on src/library/zoid/message/component.js
> +                                : getCookieByName('ts_c');
yes i should probably just assign it to null or just do a [null check ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator)

2022-04-25 20:13 UTC, paypal-rosman commented on src/library/zoid/message/component.js
> +                            getCookieByName('ts_c') !== null
yea good idea let me do that. it will be cleaner

2022-05-10 16:07 UTC, JustinDoan commented on src/utils/miscellaneous.js
> +        typeof getStorage().getState(storage => storage.ts) !== 'undefined'
Should be able to use something like

getStorage().getState(storage => storage?.ts) ? getCookieByName : getStorage().getState(storage => storage.ts)

2022-05-10 16:07 UTC, JustinDoan commented on src/utils/miscellaneous.js
> +        typeof getStorage().getState(storage => storage.ts) !== 'undefined'
Actually could shorten this further with

getStorage().getState(storage => storage?.ts) ?? getCookieByName('ts_c')

2022-05-10 16:07 UTC, JustinDoan commented on src/utils/miscellaneous.js
> +        typeof getStorage().getState(storage => storage.ts) !== 'undefined'
Depends if there is a possibility of "" being in .ts

2022-05-10 16:07 UTC, JustinDoan commented on src/utils/miscellaneous.js
> +    return cookieString ? formatTsCookie(cookieString[0]) : cookieString;
Nullish coalescing operator could be used here

2022-05-10 16:07 UTC, JustinDoan commented on src/utils/sdk.js
>          } catch (e) {
Since we are relying on isLocalStorageEnabled, do we want to log anything/err anything, maybe with ppDebug or something if this fails?

2022-05-10 16:20 UTC, paypal-rosman commented on src/utils/miscellaneous.js
> +        typeof getStorage().getState(storage => storage.ts) !== 'undefined'
no it will always be null or have a value so this 
`getStorage().getState(storage => storage?.ts) ?? getCookieByName('ts_c')`

should work, I will test it

2022-05-10 16:26 UTC, paypal-rosman commented on src/utils/miscellaneous.js
> +    return cookieString ? formatTsCookie(cookieString[0]) : cookieString;
this returns a true or false value so i am pretty Nullish coalescing wouldn't work here correct?

2022-05-10 18:57 UTC, JustinDoan commented on src/utils/miscellaneous.js
> +    return cookieString ? formatTsCookie(cookieString[0]) : cookieString;
What do you mean this returns true or false? looks like it will return null or a formatted string?

2022-05-10 20:43 UTC, paypal-rosman commented on src/utils/miscellaneous.js
> +    return cookieString ? formatTsCookie(cookieString[0]) : cookieString;
whoops you are right, not sure what i was thinking about

2022-05-20 13:52 UTC, jadutter commented on src/utils/miscellaneous.js
> +    const cookieString = document.cookie.match(`${name}=[^;]+`);
Can we revise this to not use regex?

2022-05-23 17:53 UTC, jadutter requested changes, later dismissed

2022-05-23 17:53 UTC, jadutter commented on src/utils/miscellaneous.js
> +            ?.slice(5)
```suggestion
            ?.slice(5) ?? ''
```
otherwise, 
```javascript 
cookieVal === decodeURIComponent(undefined) === 'undefined'
```
and the function will return `{undefined: ''}` instead of of `null`

2022-05-24 14:39 UTC, jadutter approved these changes

2022-05-31 19:59 UTC, merged