ci: fix unzip security
paypal/paypal-messaging-components pull request #844
Opened 2022-08-12 17:41 UTC by Seavenly

2022-08-15 13:43 UTC, merlinpatt requested changes

2022-08-15 13:43 UTC, merlinpatt commented on .github/workflows/snapshotCommit.yml
> +                          const tmpDir = `/tmp/${artifact.name.replace(/[^a-zA-Z0-9-_]/g, '')}`;
All looks good. Only change I would make is to at least have this be `tempDir` with an `e` just to be a little more clear. And `/tmp` could be `/temp` for the same reason

2022-08-15 13:54 UTC, Seavenly commented on .github/workflows/snapshotCommit.yml
> +                          const tmpDir = `/tmp/${artifact.name.replace(/[^a-zA-Z0-9-_]/g, '')}`;
For Linux base systems, `/tmp` is the official root directory where temporary files are written. For that reason the variable is named `tmpDir`. We should continue to use `/tmp`, but I'm happy to rename the variable to `tempDir` if we'd like.

2022-08-15 14:20 UTC, merlinpatt commented on .github/workflows/snapshotCommit.yml
> +                          const tmpDir = `/tmp/${artifact.name.replace(/[^a-zA-Z0-9-_]/g, '')}`;
I suppose it's fine then. I guess I'll just take it up with the creators of Linux. Lol

2022-08-16 13:49 UTC, jadutter commented on .github/workflows/snapshotCommit.yml
> +                            execSync(`rsync -zavpmr --no-links --include='pull_number.txt' --exclude='*' ${tmpDir}/ ${{ github.workspace }}`);
is `--no-links` a valid option for `rsync`?

1. [actions/github-script](https://github.com/actions/github-script/blob/main/action.yml#L30) seems to use node16
1. [node16](https://github.com/nodejs/docker-node/blob/f82af606acd44dc6be7fbb2a069922afa32657f3/16/buster/Dockerfile#L1) seems to build upon buster (a debian version).
1. [rsync package](https://packages.debian.org/bullseye/rsync) for debian links to a homepage, which contains the documentation
1. I don't see the option in the [rsync documentation](https://download.samba.org/pub/rsync/rsync.1)

I also tried it locally
```bash 
docker container run --rm -it node:16 bash
apt update && (yes | apt-get install rsync) && rsync --help 
```

Instead of `-zavpmr --no-links`, I think we want `-zvmrptgoD`, by replacing `-a` with its equivalents, but removing the `-l` option.

2022-08-16 15:00 UTC, merlinpatt approved these changes

2022-08-16 15:01 UTC, merlinpatt commented on .github/workflows/snapshotCommit.yml
> +                            execSync(`rsync -zavpmr --no-links --include='pull_number.txt' --exclude='*' ${tmpDir}/ ${{ github.workspace }}`);
Can a comment be added as to what this does? What is `-zavpmr` or `-zvmrptgoD`?

2022-08-16 17:29 UTC, jadutter approved these changes

2022-08-16 18:25 UTC, merged