refactor: Credit and Pay Later Messaging accessibility issues- tracfone.com (DTCRCMERC-1728)
paypal/paypal-messaging-components pull request #856
Opened 2022-09-22 15:50 UTC by erikacolette29

2022-10-24 14:40 UTC, merlinpatt requested changes

2022-10-24 14:40 UTC, merlinstardust commented on demo/standalone-modal.html
> +                //DEV_US_LONG_TERM_CHECKOUT'
remove

2022-10-24 14:40 UTC, merlinstardust commented on content/modals/US/v2_product_list.json
> +        "headline": "<span aria-hidden='true'>Buy now,<br />pay over time</span><span class='sr-only'>Buy now, pay over time</span>",
Let's also do this in `DE/product_list.json`

2022-10-24 14:40 UTC, merlinpatt commented on src/components/modal/v2/parts/Calculator.jsx
> +                <div role="alert" className="content-column">
As noted by [MDN docs on aria-live here](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/alert_role), I believe we should set this to be

```
<div aria-live="polite" className="content-column">
```

> Because of its intrusive nature, the alert role must be used sparingly and only in situations where the user's immediate attention is required.

2022-10-24 14:40 UTC, merlinpatt commented on src/components/modal/v2/parts/Calculator.jsx
> +                <div role="alert" className="input__wrapper transitional">
`role="alert"` isn't necessary because the input itself isn't a live region that we're changing

2022-10-24 14:40 UTC, merlinpatt commented on src/components/modal/v2/parts/Calculator.jsx
>                  {renderError(error || emptyState || isLoading)}
But we should make this 

```
<div aria-live="polite">
  {renderError(error || emptyState || isLoading)}
</div>
```

2022-10-24 14:40 UTC, merlinpatt commented on src/components/modal/v2/parts/Calculator.jsx
>                  <h3 className="title">{title}</h3>
Since we're bumping the Header `h` tags to `h2` and `h3`, this should be `h4`

2022-10-24 14:40 UTC, merlinpatt commented on src/components/modal/v2/parts/InlineLinks.jsx
> +                        aria-label="Terms and Conditions, opens new tab."
We'll need a new story for this to add `aria` stuff into our content so this isn't just English for all locales

2022-10-24 14:40 UTC, merlinpatt commented on content/offers/US/v2_long_term.json
> +            "nonZeroApr": "<span aria-hidden='true'>Est. APR*</span><span class='sr-only'>Estimated APR, see * for more details below.</span>",
Based on [this page](https://www.deque.com/blog/dont-screen-readers-read-whats-screen-part-1-punctuation-typographic-symbols/), screen readers will not read `*` at all to users. So let's replace `*` with the word `star`

2022-10-24 14:40 UTC, merlinpatt commented on src/components/modal/v2/parts/views/NoInterest/Content.jsx
> +                        <p>
This external paragraph can be removed, and the map can be simplified to just be

```
{footer.map(lineContent => (
    <p className="content__footer-item">
        <InlineLinks text={lineContent} />
    </p>
))}
```

2022-10-24 14:40 UTC, merlinpatt commented on src/server/message/index.jsx
> +                            <p className="message__headline">
Let's separate these message changes into a separate branch and separate PR just in case we need to revert one or the other.

2022-10-24 14:40 UTC, merlinpatt commented on src/server/message/parts/Logo.jsx
> +        <div className="message__logo-container" aria-hidden="true" alt="PayPal">
Include these changes as well in the separate branch / PR

2022-10-24 14:40 UTC, merlinpatt commented on src/components/modal/v2/parts/views/NoInterest/Content.jsx
> +                                        aria-describedby="Subject to Credit Approval"
This and the `InlineLinks` will need to be part of a story for translation/new content

From `InlineLinks.jsx`
```
aria-label="Terms and Conditions, opens new tab."
```

From NoInterest/Content.jsx
```
aria-describedby="Subject to Credit Approval"
```

2022-10-28 03:13 UTC, merlinpatt requested changes

2022-10-28 03:13 UTC, merlinpatt commented on src/components/modal/v2/parts/Header.jsx
> +                <h2 dangerouslySetInnerHTML={{ __html: headline }} />
Styles for h2 and h3 need to be updated so they have h1 and h2 styles respectively. The one on the left is what we want

<img width="745" alt="Screen Shot 2022-10-27 at 23 12 40" src="https://user-images.githubusercontent.com/421960/198492670-44912d7d-41ce-4809-b155-bbbbeb48cb02.png">

2022-10-31 19:10 UTC, merlinpatt approved these changes

2022-11-02 14:47 UTC, merlinpatt requested changes

2022-11-02 14:47 UTC, merlinpatt commented on src/components/modal/v2/parts/InlineLinks.jsx
> +                        aria-label="Terms and Conditions, opens new tab."
I just realized one more issue with this. The aria-label should be dynamic based on the `linkText` so it should be
```
aria-label={`${linkText}, opens new tab.`}
```

And "opens new tab" should be included the accessibility story with the other translations

2022-11-15 16:38 UTC, yeul approved these changes

2022-11-15 16:56 UTC, merged